#!/usr/bin/env python3

import sys
import os

if __name__== "__main__":
    flags = [arg for arg in sys.argv if arg[0] == '-']
    nonflags = [arg for arg in sys.argv if arg[0] != '-']

    thisFile = nonflags[0]
    while True:
        try: thisFile = os.readlink(thisFile)
        except: break
    thisDir = os.path.dirname(thisFile)
    filename, ext = os.path.splitext(nonflags[1])


    comp = '-c' in flags or '--comp' in flags or '--compile' in flags
    link = '-l' in flags or '--link' in flags
    run = '-r' in flags or '--run' in flags
    if not (comp or link or run): comp = link = run = True

    verbose = '-v' in flags or '--verbose' in flags
    def vprint(x):
        if verbose: print(f"[decaf] {x}")

    status = 0
    if comp:
        vprint(f"{thisDir}/build/parser {filename}.decaf")
        status = os.system(f"{thisDir}/build/parser {filename}.decaf")
        vprint(f"status: {status}")
        if status: sys.exit(status)
    if link:
        vprint(f"clang {thisDir}/src/decafruntime.c {filename}.o -o {filename}")
        status = os.system(f"clang {thisDir}/src/decafruntime.c {filename}.o -o {filename}")
        vprint(f"status: {status}")
        if status: sys.exit(status)
    if run:
        vprint(f"{filename}")
        status = os.system(f"{filename}")
        vprint(f"status: {status}")
        if status: sys.exit(status)


